Astina\Bundle\RedirectManagerBundle\Entity\Map:
    type: entity
    table: armb_redirect_map
    repositoryClass: Astina\Bundle\RedirectManagerBundle\Entity\MapRepository
    uniqueConstraints:
        host_urlFrom: { columns: [host, urlFrom] }
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        host:
            column: host
            type: string
            length: 255
            nullable: true
        hostIsRegexPattern:
            type: boolean
            nullable: true
        hostRegexPatternNegate:
            type: boolean
            nullable: true
        urlFrom:
            column: urlFrom
            type: string
            length: 255
        urlFromIsRegexPattern:
            type: boolean
            nullable: true
        urlFromIsNoCase:
            type: boolean
            nullable: true
        urlTo:
            type: string
            length: 255
        count:
            type: integer
        countRedirects:
            type: boolean
        redirectHttpCode:
            type: string
            length: 3
        comment:
            type: text
            nullable: true
    manyToOne:
        group:
            targetEntity: Astina\Bundle\RedirectManagerBundle\Entity\Group
            joinColumn: { onDelete: "set null" }
    lifecycleCallbacks: {  }
